#!/bin/bash --login

#SBATCH --job-name=test_job
#SBATCH --nodes=1
#SBATCH --tasks-per-node=20
#SBATCH --cpus-per-task=1
#SBATCH --time=0:5:0

# Replace [budget code] below with your project code (e.g. t01)
#SBATCH --account=n02
#SBATCH --partition=standard
#SBATCH --qos=standard

# Setup the batch environment
module load epcc-job-env

module restore PrgEnv-cray
module load cray-netcdf-hdf5parallel
module load cray-hdf5-parallel
module load cray-fftw/3.3.8.7
module load petsc/3.13.3
export HDF5_DIR=/opt/cray/pe/hdf5-parallel/default/crayclang/9.1/lib

srun --distribution=block:block --hint=nomultithread ./build/bin/monc_driver.exe -n 20 --config=dephy_20191209_12_casim.mcf
